[package]
name = "tiny-champ-select-helper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
surf = { version = "2.3.2", features = ["h1-client"]}
async-native-tls = "0.3.3"
async-std = { version = "1.8.0", features = ["attributes"] }
base64 = "0.13.0"
anyhow = "1.0.56"
# tide = "0.16.0"
# horrorshow = "0.8.4"
# async-std = { version = "1.8.0", features = ["attributes"] }
# serde = { version = "1.0", features = ["derive"] }