[package]
name = "tiny-champ-select-helper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = "4.0.17"
base64 = "0.13.0"
# tide = "0.16.0"
# horrorshow = "0.8.4"
# async-std = { version = "1.8.0", features = ["attributes"] }
# serde = { version = "1.0", features = ["derive"] }